# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: /dev/real - Terminal tools for real sustained development.
email: admin@devreal.org
description: >- # this means to ignore newlines until "baseurl:"
  Rooted in the Unix philosophy, /dev/real publishes tools that are minimal
  and composable. But we’re not just preserving old patterns — we’re
  exploring new ones. Our aim is to invent modern, efficient workflows
  that live in the terminal: fast, scriptable, transparent, and
  distraction-free.

  No layers you didn’t ask for. No surprises. Just real tools for real work.

author:
  name: Harkaitz Agirre
  email: harkaitz.aguirre@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devreal.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: devreal_org
github_username:  openvirtus

# Build settings
theme: termina-plex
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
destination: ../openvirtus.github.io/docs
termina-plex:
  date_format: "%Y %m %d"
  hostname: /dev/real
  header_links:
#    - { name: Tar, url: "/tar" }
    - { name: Style, url: "/style" }
    - { name: EnvVar, url: "/env" }
